import type {
  Engineer,
  WeldySession,
  TaskAssignment,
  KnowledgeBaseItem,
  DashboardMetrics,
  ActivityEvent,
} from "./types";

// ── Engineers ────────────────────────────────────────────────────────

export const engineers: Engineer[] = [
  {
    id: "eng-1",
    name: "Aristogiannis",
    initials: "AR",
    status: "busy",
    currentTaskId: "replace-spark-plugs",
    phone: "+49 171 234 5678",
    specialties: ["engine", "electrical"],
    tasksCompletedToday: 3,
    totalTasksCompleted: 147,
    avgCompletionMinutes: 16,
    joinedDate: "2024-03-15",
  },
  {
    id: "eng-2",
    name: "Maria Santos",
    initials: "MS",
    status: "online",
    currentTaskId: null,
    phone: "+49 172 345 6789",
    specialties: ["brakes", "tyres", "exterior"],
    tasksCompletedToday: 2,
    totalTasksCompleted: 98,
    avgCompletionMinutes: 22,
    joinedDate: "2024-06-01",
  },
  {
    id: "eng-3",
    name: "Thomas Weber",
    initials: "TW",
    status: "busy",
    currentTaskId: "check-engine-oil",
    phone: "+49 173 456 7890",
    specialties: ["engine", "slk-specific"],
    tasksCompletedToday: 4,
    totalTasksCompleted: 203,
    avgCompletionMinutes: 14,
    joinedDate: "2023-11-10",
  },
  {
    id: "eng-4",
    name: "Leila Haddad",
    initials: "LH",
    status: "offline",
    currentTaskId: null,
    phone: "+49 174 567 8901",
    specialties: ["engine", "brakes", "dashboard", "exterior"],
    tasksCompletedToday: 0,
    totalTasksCompleted: 176,
    avgCompletionMinutes: 19,
    joinedDate: "2024-01-20",
  },
  {
    id: "eng-5",
    name: "Jonas Eriksen",
    initials: "JE",
    status: "busy",
    currentTaskId: "inspect-brake-pads-discs",
    phone: "+49 175 678 9012",
    specialties: ["brakes", "tyres"],
    tasksCompletedToday: 1,
    totalTasksCompleted: 34,
    avgCompletionMinutes: 25,
    joinedDate: "2025-01-08",
  },
];

// ── Knowledge Base (from real product) ───────────────────────────────

export const knowledgeBase: KnowledgeBaseItem[] = [
  {
    id: "check-engine-oil",
    title: "Check and Top Up Engine Oil",
    category: "engine",
    keywords: ["oil", "dipstick", "engine oil", "oil level", "top up oil", "low oil", "oil cap", "M111"],
    totalSteps: 9,
    estimatedMinutes: 10,
    lastUpdated: "2025-02-20T10:30:00Z",
    updatedBy: "Admin",
    content: `## Check and Top Up Engine Oil — Mercedes SLK 200 (R170)\n\n**Engine:** M111.946 — 2.0L Inline-4, 16-valve, naturally aspirated.\n\n**Oil specification:** Mercedes-Benz spec 229.1 or 229.3. Recommended viscosity is 5W-40 or 0W-40 fully synthetic. Total oil capacity with filter is approximately 5.5 litres.\n\n### Steps\n\n1. Park the car on a level surface and turn off the engine. Wait at least 5 minutes for the oil to settle back into the sump.\n2. Open the bonnet — the release lever is on the left side of the footwell, near the door. Pull it, then lift the bonnet and secure it with the prop rod.\n3. Locate the dipstick — it's on the left side of the engine (passenger side in LHD cars), with a yellow loop handle.\n4. Pull the dipstick out and wipe it clean with a lint-free cloth.\n5. Re-insert the dipstick fully, then pull it out again and hold it horizontally.\n6. Read the oil level — the oil film should sit between the MIN and MAX markings.\n7. If the level is near or below MIN, remove the oil filler cap on top of the engine and add oil in 250ml increments.\n8. Do not overfill beyond the MAX mark — overfilling can damage seals and the catalytic converter.\n9. Replace the dipstick and oil filler cap, close the bonnet, and you're done.`,
  },
  {
    id: "change-engine-oil-filter",
    title: "Change Engine Oil and Oil Filter",
    category: "engine",
    keywords: ["oil change", "oil filter", "drain plug", "sump", "oil service", "engine service"],
    totalSteps: 13,
    estimatedMinutes: 45,
    lastUpdated: "2025-02-18T14:00:00Z",
    updatedBy: "Admin",
    content: `## Change Engine Oil and Oil Filter — Mercedes SLK 200 (R170)\n\n**You will need:** 5.5L of 5W-40 or 0W-40 fully synthetic oil (MB 229.1/229.3 spec), a new oil filter (Mann W712/22 or equivalent), a new drain plug crush washer (14mm copper), a 13mm socket for the drain plug, an oil filter wrench, a drain pan, and jack stands or ramps.\n\n### Steps\n\n1. Warm the engine to operating temperature — a short 5 minute drive is enough.\n2. Lift the car on ramps or jack stands. Make sure it is level and secure.\n3. Place the drain pan under the sump. The drain plug is at the very bottom rear of the oil sump.\n4. Using the 13mm socket, loosen the drain plug anti-clockwise.\n5. Let the oil drain fully — this takes about 10 minutes.\n6. While it drains, locate the oil filter on the left side of the engine block.\n7. Before fitting the new filter, lightly coat the rubber gasket ring with fresh oil.\n8. Hand-tighten the new filter — turn it until the gasket contacts the block, then tighten another three-quarter turn.\n9. Replace the drain plug with a new crush washer and tighten to 25 Nm.\n10. Lower the car, then add approximately 5 litres of fresh oil through the filler cap.\n11. Start the engine and let it idle for 30 seconds.\n12. Turn the engine off, wait 2 minutes, then check the level with the dipstick.\n13. Reset the service indicator if applicable.`,
  },
  {
    id: "check-coolant-level",
    title: "Check and Top Up Coolant",
    category: "engine",
    keywords: ["coolant", "antifreeze", "coolant level", "expansion tank", "overheating", "radiator"],
    totalSteps: 8,
    estimatedMinutes: 8,
    lastUpdated: "2025-02-15T09:00:00Z",
    updatedBy: "Admin",
    content: `## Check and Top Up Coolant — Mercedes SLK 200 (R170)\n\n**Coolant spec:** Mercedes-Benz genuine anticorrosion/antifreeze agent (blue), mixed 50/50 with distilled water.\n\n### Steps\n\n1. **IMPORTANT:** Only check coolant when the engine is COLD.\n2. Open the bonnet.\n3. Locate the coolant expansion tank — translucent plastic reservoir on the right side, near the firewall. Blue cap.\n4. Check the level visually — coolant should be between MIN and MAX marks.\n5. If low, carefully unscrew the blue cap.\n6. Add a 50/50 mix of Mercedes-approved antifreeze and distilled water.\n7. Fill to the MAX mark, but no higher. Replace the cap.\n8. If you're regularly losing coolant, check for leaks at the water pump, thermostat housing, and radiator end tanks.`,
  },
  {
    id: "check-brake-fluid",
    title: "Check Brake Fluid Level",
    category: "engine",
    keywords: ["brake fluid", "DOT 4", "brake reservoir", "brake warning", "brake level"],
    totalSteps: 7,
    estimatedMinutes: 5,
    lastUpdated: "2025-02-10T11:00:00Z",
    updatedBy: "Admin",
    content: `## Check Brake Fluid Level — Mercedes SLK 200 (R170)\n\n**Brake fluid spec:** DOT 4 Plus (Mercedes-Benz spec 331.0).\n\n### Steps\n\n1. Open the bonnet.\n2. Locate the brake fluid reservoir — rear of the engine bay, in front of windscreen, slightly to the left.\n3. The reservoir is translucent — read the level without opening. Fluid should be between MIN and MAX.\n4. If low, clean the area around the cap before opening.\n5. Unscrew the cap and top up with fresh DOT 4 Plus fluid to the MAX line.\n6. If the fluid looks very dark, it's time for a full brake fluid flush.\n7. Replace the cap firmly.`,
  },
  {
    id: "check-top-up-washer-fluid",
    title: "Top Up Windscreen Washer Fluid",
    category: "engine",
    keywords: ["washer fluid", "windscreen", "wiper fluid", "screen wash"],
    totalSteps: 7,
    estimatedMinutes: 3,
    lastUpdated: "2025-01-30T08:00:00Z",
    updatedBy: "Admin",
    content: `## Top Up Windscreen Washer Fluid — Mercedes SLK 200 (R170)\n\n### Steps\n\n1. Open the bonnet.\n2. Locate the washer fluid reservoir — right side, cap has a windscreen wiper symbol.\n3. Pull off or unscrew the cap.\n4. Fill with a mixture of screen wash concentrate and water.\n5. The reservoir holds approximately 4 litres.\n6. Replace the cap.\n7. Test the washers from the driver's seat.`,
  },
  {
    id: "replace-air-filter",
    title: "Replace Engine Air Filter",
    category: "engine",
    keywords: ["air filter", "air box", "intake", "filter change", "air cleaner"],
    totalSteps: 8,
    estimatedMinutes: 15,
    lastUpdated: "2025-02-05T16:00:00Z",
    updatedBy: "Admin",
    content: `## Replace Engine Air Filter — Mercedes SLK 200 (R170)\n\n**Filter type:** Panel filter — Mann C25114 or equivalent.\n\n### Steps\n\n1. Open the bonnet.\n2. Locate the air filter box — large black plastic housing on the left side.\n3. Unclip the metal spring clips on the air box lid (usually 4 clips).\n4. Carefully lift the lid and note the orientation of the old filter.\n5. Remove the old filter. Wipe out any dirt from inside the air box.\n6. Drop the new filter in, making sure it seats flat.\n7. Replace the lid and re-secure all clips.\n8. Make sure the intake duct is properly reconnected.`,
  },
  {
    id: "replace-spark-plugs",
    title: "Replace Spark Plugs",
    category: "engine",
    keywords: ["spark plugs", "ignition", "misfire", "rough idle", "tune up"],
    totalSteps: 12,
    estimatedMinutes: 35,
    lastUpdated: "2025-02-12T13:00:00Z",
    updatedBy: "Admin",
    content: `## Replace Spark Plugs — Mercedes SLK 200 (R170)\n\n**Engine:** M111.946 — 4 cylinders, 4 spark plugs.\n**Spark plug spec:** Bosch FR8DC+. Gap: 0.8mm. Socket size: 16mm.\n\n### Steps\n\n1. Let the engine cool completely.\n2. Open the bonnet and remove the plastic engine cover.\n3. Identify the 4 ignition coil packs on top of the cylinder head.\n4. Disconnect the electrical connector from the first coil pack.\n5. Remove the coil pack bolt and pull the coil pack straight up.\n6. Use a 16mm spark plug socket with extension to reach into the well.\n7. Unscrew the old plug anti-clockwise.\n8. Check the new plug's gap — should be 0.8mm.\n9. Hand-thread the new plug clockwise. Torque to 25 Nm.\n10. Reinstall the coil pack and reconnect the connector.\n11. Repeat for all 4 cylinders.\n12. Replace the engine cover, start the engine, verify smooth idle.`,
  },
  {
    id: "serpentine-belt-inspection",
    title: "Inspect and Replace Serpentine Belt",
    category: "engine",
    keywords: ["serpentine belt", "drive belt", "belt squeal", "belt tensioner", "alternator belt"],
    totalSteps: 12,
    estimatedMinutes: 30,
    lastUpdated: "2025-01-28T10:00:00Z",
    updatedBy: "Admin",
    content: `## Inspect and Replace Serpentine Belt — Mercedes SLK 200 (R170)\n\n**Belt type:** Single serpentine belt driving alternator, power steering pump, water pump, and A/C compressor.\n\n### Inspection\n\n1. Open the bonnet and look at the front of the engine.\n2. Visually inspect the belt for cracks, fraying, or glazing.\n3. Press the belt between two pulleys — no more than 10mm deflection.\n4. Listen for squealing on cold start.\n5. If any issues found, proceed with replacement.\n\n### Replacement\n\n6. Use a 17mm socket on the tensioner bolt.\n7. Rotate the tensioner clockwise to release tension.\n8. Slip the old belt off. Take a photo of the routing first.\n9. Route the new belt around all pulleys except the tensioner.\n10. Rotate the tensioner and slip the belt onto the tensioner pulley last.\n11. Release the tensioner slowly — verify belt is seated in every groove.\n12. Start the engine and watch for 30 seconds to confirm proper tracking.`,
  },
  {
    id: "dashboard-warning-lights",
    title: "Dashboard Warning Lights Explained",
    category: "dashboard",
    keywords: ["warning light", "dashboard light", "check engine", "oil light", "ABS light", "SRS"],
    totalSteps: 0,
    estimatedMinutes: 5,
    lastUpdated: "2025-02-22T12:00:00Z",
    updatedBy: "Admin",
    content: `## Dashboard Warning Lights — Mercedes SLK 200 (R170)\n\n### Red Lights (Stop Driving / Immediate Attention)\n\n- **Oil Pressure:** Engine oil pressure is critically low. Stop immediately.\n- **Coolant Temperature:** Engine is overheating. Pull over safely.\n- **Brake Warning:** Handbrake on, or brake fluid critically low.\n- **Battery / Charging:** Alternator is not charging. Drive to safety.\n- **SRS / Airbag:** Airbag system fault.\n\n### Yellow / Amber Lights (Caution)\n\n- **Check Engine:** Engine management fault. Usually safe to drive.\n- **ABS:** Anti-lock braking fault. Normal brakes still work.\n- **ESP / BAS:** Stability control fault.\n- **Low Fuel:** Approximately 8 litres remaining.\n\n### Green / Blue Lights (Information)\n\n- **Turn signals:** Indicator active.\n- **High beam:** High beams are on.\n- **Cruise control:** Cruise control is active.`,
  },
  {
    id: "reset-service-indicator",
    title: "Reset Service Indicator",
    category: "dashboard",
    keywords: ["service indicator", "service reset", "maintenance light", "service due", "assyst"],
    totalSteps: 8,
    estimatedMinutes: 5,
    lastUpdated: "2025-02-01T14:00:00Z",
    updatedBy: "Admin",
    content: `## Reset Service Indicator — Mercedes SLK 200 (R170)\n\nThe R170 SLK uses the Flexible Service System (FSS).\n\n### Steps\n\n1. Sit in the driver's seat and close the door.\n2. Insert the key but do NOT turn it.\n3. Press and HOLD the trip odometer reset button.\n4. While holding, turn the ignition key to position 2.\n5. Continue holding for about 10 seconds until the display resets.\n6. Release the button.\n7. Turn the ignition off and remove the key.\n8. Start the engine to verify — service indicator should be gone.`,
  },
  {
    id: "check-tyre-pressure",
    title: "Check and Adjust Tyre Pressure",
    category: "tyres",
    keywords: ["tyre pressure", "tire pressure", "inflate", "PSI", "bar", "205/60 R15"],
    totalSteps: 7,
    estimatedMinutes: 10,
    lastUpdated: "2025-02-14T09:00:00Z",
    updatedBy: "Admin",
    content: `## Check and Adjust Tyre Pressure — Mercedes SLK 200 (R170)\n\n**Tyre size:** 205/60 R15.\n**Recommended:** 2.2 bar (32 PSI) front, 2.4 bar (35 PSI) rear.\n\n### Steps\n\n1. Check when tyres are COLD — parked at least 2 hours.\n2. Remove the valve cap from the valve stem.\n3. Press the pressure gauge firmly onto the valve. Read the pressure.\n4. If too low, inflate in short bursts. Recheck between bursts.\n5. If too high, press the pin in the valve to release air.\n6. Replace the valve cap.\n7. Repeat for all four tyres and the spare.`,
  },
  {
    id: "change-flat-tyre",
    title: "Change a Flat Tyre",
    category: "tyres",
    keywords: ["flat tyre", "spare wheel", "jack", "wheel nuts", "puncture", "roadside"],
    totalSteps: 13,
    estimatedMinutes: 25,
    lastUpdated: "2025-01-25T11:00:00Z",
    updatedBy: "Admin",
    content: `## Change a Flat Tyre — Mercedes SLK 200 (R170)\n\n**Wheel nut size:** 17mm. **Torque spec:** 110 Nm.\n\n### Steps\n\n1. Pull over to a safe, flat, hard surface. Hazard lights on.\n2. Apply handbrake, leave in 1st gear.\n3. Locate jack and wheel brace in the boot.\n4. Loosen each wheel bolt by half a turn (anti-clockwise).\n5. Position the jack under the reinforced jacking point on the sill.\n6. Raise the car until the flat tyre is 2-3 cm off the ground.\n7. Fully remove the wheel bolts and pull the wheel off.\n8. Mount the spare wheel, aligning bolt holes. Hand-tighten bolts in star pattern.\n9. Lower the jack until tyre touches ground (not full weight).\n10. Tighten all bolts firmly in star pattern.\n11. Lower the car fully and remove the jack.\n12. Final-tighten all bolts. Torque to 110 Nm when possible.\n13. Stow flat tyre and tools. If space-saver, do not exceed 80 km/h.`,
  },
  {
    id: "inspect-brake-pads-discs",
    title: "Inspect Brake Pads and Discs",
    category: "brakes",
    keywords: ["brake pads", "brake discs", "brake rotors", "worn brakes", "grinding", "squealing"],
    totalSteps: 5,
    estimatedMinutes: 20,
    lastUpdated: "2025-02-08T15:00:00Z",
    updatedBy: "Admin",
    content: `## Inspect Brake Pads and Discs — Mercedes SLK 200 (R170)\n\n**Front brakes:** Ventilated discs, 288mm. **Rear:** Solid discs, 278mm.\n\n### Visual Inspection\n\n1. Turn steering to full lock to view front brakes through wheel spokes.\n2. Look at the brake caliper — estimate pad thickness (new pads: 10-12mm, replace at 3mm).\n3. Check disc surface — should be smooth. Deep scoring or blue marks mean replacement.\n4. For accurate measurement, remove the wheel and use a vernier caliper.\n5. Always replace pads in pairs — both sides of the same axle.`,
  },
  {
    id: "replace-headlight-bulb",
    title: "Replace Headlight Bulb",
    category: "exterior",
    keywords: ["headlight", "headlamp", "bulb", "H7", "H1", "low beam", "high beam"],
    totalSteps: 11,
    estimatedMinutes: 15,
    lastUpdated: "2025-02-03T10:00:00Z",
    updatedBy: "Admin",
    content: `## Replace Headlight Bulb — Mercedes SLK 200 (R170)\n\n**Bulb types:** Low beam: H7 (55W). High beam: H1 (55W). Parking: W5W.\n\n### Steps — Low Beam (H7)\n\n1. Open the bonnet.\n2. Locate the back of the headlight assembly.\n3. Disconnect the electrical connector.\n4. Remove the rubber dust cap.\n5. Press the wire retaining clip inward and swing it away.\n6. Pull the old bulb straight out.\n7. Insert new H7 bulb — do NOT touch the glass with fingers.\n8. Secure the wire retaining clip.\n9. Replace the rubber dust cap.\n10. Reconnect the electrical connector.\n11. Test the light before closing the bonnet.`,
  },
  {
    id: "replace-tail-light-bulb",
    title: "Replace Tail Light or Brake Light Bulb",
    category: "exterior",
    keywords: ["tail light", "brake light", "rear light", "indicator bulb", "P21W"],
    totalSteps: 9,
    estimatedMinutes: 10,
    lastUpdated: "2025-01-20T14:00:00Z",
    updatedBy: "Admin",
    content: `## Replace Tail Light / Brake Light Bulb — Mercedes SLK 200 (R170)\n\n**Common bulbs:** Brake: P21W. Tail+brake: P21/5W. Indicator: PY21W. Reverse: P21W.\n\n### Steps\n\n1. Open the boot.\n2. Locate the tail light access panel behind the affected light cluster.\n3. Turn the relevant bulb holder anti-clockwise and pull it out.\n4. Push the old bulb in and turn anti-clockwise to release.\n5. Pull the old bulb out.\n6. Insert the new bulb — push in and turn clockwise until it clicks.\n7. Reinsert the holder and turn clockwise to lock.\n8. Test the light.\n9. Replace the boot lining or cover panel.`,
  },
  {
    id: "operate-vario-roof",
    title: "Operate the Retractable Vario Roof",
    category: "slk-specific",
    keywords: ["vario roof", "retractable roof", "hardtop", "convertible", "roof open", "roof close"],
    totalSteps: 7,
    estimatedMinutes: 5,
    lastUpdated: "2025-02-17T11:00:00Z",
    updatedBy: "Admin",
    content: `## Operate the Retractable Vario Roof — Mercedes SLK 200 (R170)\n\nThe SLK R170 was the first production car with an automatic folding metal hardtop.\n\n### Prerequisites\n\n- Car must be stationary. Handbrake engaged. Engine running.\n- Boot must have enough space for the roof to fold in.\n\n### Opening the Roof\n\n1. Make sure windows are fully closed.\n2. Press and hold the roof switch on the centre console.\n3. Continue holding until the roof has fully folded into the boot.\n4. Do not release until the operation is completely finished.\n\n### Closing the Roof\n\n5. Press and hold the roof switch in the opposite direction.\n6. The boot lid opens, roof unfolds and swings forward.\n7. Hold until fully latched.`,
  },
  {
    id: "slk-fuse-box-locations",
    title: "Fuse Box Locations and Common Fuses",
    category: "slk-specific",
    keywords: ["fuse", "fuse box", "blown fuse", "electrical", "relay", "no power"],
    totalSteps: 6,
    estimatedMinutes: 10,
    lastUpdated: "2025-01-15T09:00:00Z",
    updatedBy: "Admin",
    content: `## Fuse Box Locations — Mercedes SLK 200 (R170)\n\nThe R170 has two main fuse boxes.\n\n### 1. Interior Fuse Box\n\n- **Location:** Left side of dashboard, behind removable panel near driver's left knee.\n- Key fuses: Cigarette lighter (15A), Radio (10A), Power windows (20A), Roof mechanism (25A).\n\n### 2. Engine Bay Fuse Box\n\n- **Location:** Left side of engine bay, near battery. Black plastic cover.\n- Key fuses: Fuel pump (15A), ECU (10A), Headlights (10A each), ABS (30A).\n\n### How to Replace\n\n1. Turn ignition off.\n2. Locate the fuse using the diagram on the fuse box cover.\n3. Pull the fuse straight out with the fuse puller tool.\n4. Hold up to light — if the wire inside is broken, it's blown.\n5. Replace with same amperage rating. Never uprate.\n6. If the new fuse blows immediately, there's a short circuit — have it inspected.`,
  },
  {
    id: "slk-vehicle-specs",
    title: "SLK 200 Vehicle Specifications and Overview",
    category: "slk-specific",
    keywords: ["specs", "specifications", "SLK 200", "R170", "horsepower", "torque", "weight"],
    totalSteps: 0,
    estimatedMinutes: 3,
    lastUpdated: "2025-02-25T08:00:00Z",
    updatedBy: "Admin",
    content: `## Mercedes-Benz SLK 200 (R170) — Full Specifications\n\n### Engine\n- **Type:** M111.946 — Inline 4-cylinder, 16 valves\n- **Displacement:** 1,998 cc (2.0 litres)\n- **Power:** 136 PS (134 HP) at 5,500 rpm\n- **Torque:** 190 Nm at 3,700 rpm\n\n### Performance\n- **0-100 km/h:** 9.7 seconds\n- **Top speed:** 208 km/h\n\n### Dimensions\n- **Length:** 4,000 mm\n- **Width:** 1,720 mm\n- **Height:** 1,280 mm\n- **Kerb weight:** 1,170 kg\n\n### Brakes\n- **Front:** Ventilated discs — 288 mm\n- **Rear:** Solid discs — 278 mm\n\n### Tyres\n- **Standard:** 205/60 R15`,
  },
  {
    id: "check-battery-jump-start",
    title: "Check Car Battery and Jump Start",
    category: "electrical",
    keywords: ["battery", "dead battery", "jump start", "won't start", "jumper cables", "flat battery"],
    totalSteps: 10,
    estimatedMinutes: 20,
    lastUpdated: "2025-02-19T16:00:00Z",
    updatedBy: "Admin",
    content: `## Check Battery and Jump Start — Mercedes SLK 200 (R170)\n\n**Battery location:** Under the bonnet, right side. 12V, typically 70Ah, 570-640 CCA.\n\n### Checking the Battery\n\n1. Open the bonnet and visually inspect for corrosion or damage.\n2. With a multimeter, check voltage: 12.6V+ is healthy. Below 12.2V is significantly discharged.\n3. With engine running, should read 13.8-14.4V (alternator charging).\n\n### Jump Starting\n\n4. Position donor car close. Cars must NOT touch.\n5. RED cable: dead battery positive (+) to donor positive (+).\n6. BLACK cable: donor negative (-) to unpainted metal on SLK engine block.\n7. Start donor car, idle 2-3 minutes.\n8. Start the SLK.\n9. Remove cables in reverse order: black SLK, black donor, red donor, red SLK.\n10. Drive at least 20-30 minutes to recharge.`,
  },
];

// ── Helper to create timestamps relative to a fixed anchor ───────────
// Use a single fixed anchor so server and client produce identical values.

const ANCHOR = new Date("2026-03-01T10:00:00Z").getTime();

function hoursAgo(h: number): string {
  return new Date(ANCHOR - h * 3600000).toISOString();
}

function minutesAgo(m: number): string {
  return new Date(ANCHOR - m * 60000).toISOString();
}

function daysFromNow(d: number): string {
  return new Date(ANCHOR + d * 86400000).toISOString().split("T")[0];
}

function daysAgo(d: number): string {
  return new Date(ANCHOR - d * 86400000).toISOString().split("T")[0];
}

// ── Sessions ─────────────────────────────────────────────────────────

export const sessions: WeldySession[] = [
  {
    id: "ses-1",
    engineerId: "eng-1",
    engineerName: "Aristogiannis",
    taskId: "replace-spark-plugs",
    taskTitle: "Replace Spark Plugs",
    taskCategory: "engine",
    startTime: minutesAgo(23),
    endTime: null,
    status: "active",
    currentStep: 7,
    totalSteps: 12,
    lastActivity: "Unscrewing old spark plug from cylinder 3",
  },
  {
    id: "ses-2",
    engineerId: "eng-3",
    engineerName: "Thomas Weber",
    taskId: "check-engine-oil",
    taskTitle: "Check and Top Up Engine Oil",
    taskCategory: "engine",
    startTime: minutesAgo(8),
    endTime: null,
    status: "active",
    currentStep: 4,
    totalSteps: 9,
    lastActivity: "Wiping dipstick clean with cloth",
  },
  {
    id: "ses-3",
    engineerId: "eng-5",
    engineerName: "Jonas Eriksen",
    taskId: "inspect-brake-pads-discs",
    taskTitle: "Inspect Brake Pads and Discs",
    taskCategory: "brakes",
    startTime: minutesAgo(15),
    endTime: null,
    status: "active",
    currentStep: 2,
    totalSteps: 5,
    lastActivity: "Estimating pad thickness through wheel spokes",
  },
  {
    id: "ses-4",
    engineerId: "eng-2",
    engineerName: "Maria Santos",
    taskId: "check-tyre-pressure",
    taskTitle: "Check and Adjust Tyre Pressure",
    taskCategory: "tyres",
    startTime: minutesAgo(45),
    endTime: null,
    status: "paused",
    currentStep: 4,
    totalSteps: 7,
    lastActivity: "Paused — waiting for air compressor",
  },
  {
    id: "ses-5",
    engineerId: "eng-3",
    engineerName: "Thomas Weber",
    taskId: "check-coolant-level",
    taskTitle: "Check and Top Up Coolant",
    taskCategory: "engine",
    startTime: hoursAgo(2),
    endTime: minutesAgo(90),
    status: "completed",
    currentStep: 8,
    totalSteps: 8,
    lastActivity: "Task completed successfully",
  },
  {
    id: "ses-6",
    engineerId: "eng-1",
    engineerName: "Aristogiannis",
    taskId: "replace-air-filter",
    taskTitle: "Replace Engine Air Filter",
    taskCategory: "engine",
    startTime: hoursAgo(3),
    endTime: hoursAgo(2.5),
    status: "completed",
    currentStep: 8,
    totalSteps: 8,
    lastActivity: "Task completed successfully",
  },
  {
    id: "ses-7",
    engineerId: "eng-2",
    engineerName: "Maria Santos",
    taskId: "replace-headlight-bulb",
    taskTitle: "Replace Headlight Bulb",
    taskCategory: "exterior",
    startTime: hoursAgo(4),
    endTime: hoursAgo(3.5),
    status: "completed",
    currentStep: 11,
    totalSteps: 11,
    lastActivity: "Task completed successfully",
  },
  {
    id: "ses-8",
    engineerId: "eng-5",
    engineerName: "Jonas Eriksen",
    taskId: "check-top-up-washer-fluid",
    taskTitle: "Top Up Windscreen Washer Fluid",
    taskCategory: "engine",
    startTime: hoursAgo(5),
    endTime: hoursAgo(4.9),
    status: "completed",
    currentStep: 7,
    totalSteps: 7,
    lastActivity: "Task completed successfully",
  },
];

// ── Task Assignments ─────────────────────────────────────────────────

export const assignments: TaskAssignment[] = [
  {
    id: "asgn-1",
    taskId: "replace-spark-plugs",
    taskTitle: "Replace Spark Plugs",
    engineerId: "eng-1",
    engineerName: "Aristogiannis",
    priority: "high",
    status: "in-progress",
    assignedAt: hoursAgo(1),
    dueDate: daysFromNow(0),
    completedAt: null,
    notes: "Customer reported rough idle — priority fix",
  },
  {
    id: "asgn-2",
    taskId: "check-engine-oil",
    taskTitle: "Check and Top Up Engine Oil",
    engineerId: "eng-3",
    engineerName: "Thomas Weber",
    priority: "medium",
    status: "in-progress",
    assignedAt: hoursAgo(0.5),
    dueDate: daysFromNow(0),
    completedAt: null,
    notes: "Routine pre-delivery check",
  },
  {
    id: "asgn-3",
    taskId: "inspect-brake-pads-discs",
    taskTitle: "Inspect Brake Pads and Discs",
    engineerId: "eng-5",
    engineerName: "Jonas Eriksen",
    priority: "high",
    status: "in-progress",
    assignedAt: hoursAgo(0.5),
    dueDate: daysFromNow(0),
    completedAt: null,
    notes: "Customer complaint about squealing",
  },
  {
    id: "asgn-4",
    taskId: "change-engine-oil-filter",
    taskTitle: "Change Engine Oil and Oil Filter",
    engineerId: "eng-2",
    engineerName: "Maria Santos",
    priority: "medium",
    status: "pending",
    assignedAt: hoursAgo(2),
    dueDate: daysFromNow(1),
    completedAt: null,
    notes: "Scheduled service — 10,000 km interval",
  },
  {
    id: "asgn-5",
    taskId: "check-coolant-level",
    taskTitle: "Check and Top Up Coolant",
    engineerId: "eng-3",
    engineerName: "Thomas Weber",
    priority: "low",
    status: "completed",
    assignedAt: hoursAgo(3),
    dueDate: daysFromNow(0),
    completedAt: minutesAgo(90),
    notes: "",
  },
  {
    id: "asgn-6",
    taskId: "replace-air-filter",
    taskTitle: "Replace Engine Air Filter",
    engineerId: "eng-1",
    engineerName: "Aristogiannis",
    priority: "low",
    status: "completed",
    assignedAt: hoursAgo(4),
    dueDate: daysFromNow(0),
    completedAt: hoursAgo(2.5),
    notes: "",
  },
  {
    id: "asgn-7",
    taskId: "replace-headlight-bulb",
    taskTitle: "Replace Headlight Bulb",
    engineerId: "eng-2",
    engineerName: "Maria Santos",
    priority: "medium",
    status: "completed",
    assignedAt: hoursAgo(5),
    dueDate: daysFromNow(0),
    completedAt: hoursAgo(3.5),
    notes: "Left headlight — H7 low beam",
  },
  {
    id: "asgn-8",
    taskId: "serpentine-belt-inspection",
    taskTitle: "Inspect and Replace Serpentine Belt",
    engineerId: "eng-4",
    engineerName: "Leila Haddad",
    priority: "high",
    status: "overdue",
    assignedAt: hoursAgo(48),
    dueDate: daysAgo(1),
    completedAt: null,
    notes: "Belt squealing reported — engineer offline since yesterday",
  },
  {
    id: "asgn-9",
    taskId: "check-battery-jump-start",
    taskTitle: "Check Car Battery and Jump Start",
    engineerId: "eng-3",
    engineerName: "Thomas Weber",
    priority: "medium",
    status: "pending",
    assignedAt: hoursAgo(1),
    dueDate: daysFromNow(2),
    completedAt: null,
    notes: "Weak battery suspected — customer says slow crank",
  },
  {
    id: "asgn-10",
    taskId: "operate-vario-roof",
    taskTitle: "Operate the Retractable Vario Roof",
    engineerId: "eng-2",
    engineerName: "Maria Santos",
    priority: "low",
    status: "pending",
    assignedAt: minutesAgo(30),
    dueDate: daysFromNow(3),
    completedAt: null,
    notes: "Customer says roof stops mid-cycle — diagnose",
  },
  {
    id: "asgn-11",
    taskId: "serpentine-belt-inspection",
    taskTitle: "Inspect and Replace Serpentine Belt",
    engineerId: "eng-1",
    engineerName: "Aristogiannis",
    priority: "low",
    status: "pending",
    assignedAt: minutesAgo(60),
    dueDate: daysFromNow(1),
    completedAt: null,
    notes: "Routine inspection — check for wear",
  },
];

// ── Activity Events ──────────────────────────────────────────────────

export const activityEvents: ActivityEvent[] = [
  {
    id: "evt-1",
    type: "session_started",
    message: "Aristogiannis started working on Replace Spark Plugs",
    timestamp: minutesAgo(23),
    engineerName: "Aristogiannis",
    taskTitle: "Replace Spark Plugs",
  },
  {
    id: "evt-2",
    type: "session_started",
    message: "Jonas Eriksen started working on Inspect Brake Pads and Discs",
    timestamp: minutesAgo(15),
    engineerName: "Jonas Eriksen",
    taskTitle: "Inspect Brake Pads and Discs",
  },
  {
    id: "evt-3",
    type: "task_assigned",
    message: "Operate the Retractable Vario Roof assigned to Maria Santos",
    timestamp: minutesAgo(30),
    engineerName: "Maria Santos",
    taskTitle: "Operate the Retractable Vario Roof",
  },
  {
    id: "evt-4",
    type: "session_started",
    message: "Thomas Weber started working on Check and Top Up Engine Oil",
    timestamp: minutesAgo(8),
    engineerName: "Thomas Weber",
    taskTitle: "Check and Top Up Engine Oil",
  },
  {
    id: "evt-5",
    type: "session_completed",
    message: "Thomas Weber completed Check and Top Up Coolant in 18 min",
    timestamp: minutesAgo(90),
    engineerName: "Thomas Weber",
    taskTitle: "Check and Top Up Coolant",
  },
  {
    id: "evt-6",
    type: "session_completed",
    message: "Aristogiannis completed Replace Engine Air Filter in 14 min",
    timestamp: hoursAgo(2.5),
    engineerName: "Aristogiannis",
    taskTitle: "Replace Engine Air Filter",
  },
  {
    id: "evt-7",
    type: "engineer_offline",
    message: "Leila Haddad went offline",
    timestamp: hoursAgo(3),
    engineerName: "Leila Haddad",
  },
  {
    id: "evt-8",
    type: "session_completed",
    message: "Maria Santos completed Replace Headlight Bulb in 12 min",
    timestamp: hoursAgo(3.5),
    engineerName: "Maria Santos",
    taskTitle: "Replace Headlight Bulb",
  },
  {
    id: "evt-9",
    type: "engineer_online",
    message: "Jonas Eriksen came online",
    timestamp: hoursAgo(1),
    engineerName: "Jonas Eriksen",
  },
  {
    id: "evt-10",
    type: "kb_updated",
    message: "Knowledge base updated: SLK 200 Vehicle Specifications",
    timestamp: hoursAgo(5),
    taskTitle: "SLK 200 Vehicle Specifications and Overview",
  },
  {
    id: "evt-11",
    type: "session_completed",
    message: "Jonas Eriksen completed Top Up Windscreen Washer Fluid in 4 min",
    timestamp: hoursAgo(4.9),
    engineerName: "Jonas Eriksen",
    taskTitle: "Top Up Windscreen Washer Fluid",
  },
  {
    id: "evt-12",
    type: "task_assigned",
    message: "Check Car Battery and Jump Start assigned to Thomas Weber",
    timestamp: hoursAgo(1),
    engineerName: "Thomas Weber",
    taskTitle: "Check Car Battery and Jump Start",
  },
];

// ── Dashboard Metrics ────────────────────────────────────────────────

export const dashboardMetrics: DashboardMetrics = {
  activeSessions: 3,
  completedToday: 7,
  avgCompletionMinutes: 18,
  successRate: 94,
  engineersOnline: 3,
  engineersTotal: 5,
  tasksInQueue: 4,
  overdueAssignments: 1,
};

// ── Weekly completion data for chart ─────────────────────────────────

export const weeklyCompletions = [
  { day: "Mon", completed: 12 },
  { day: "Tue", completed: 9 },
  { day: "Wed", completed: 15 },
  { day: "Thu", completed: 11 },
  { day: "Fri", completed: 8 },
  { day: "Sat", completed: 7 },
  { day: "Today", completed: 7 },
];
